;;======================================================
;;;   Ingredients Database
;;;
;;;     Ingredient categories for dietary filtering
;;======================================================

(deffunction MAIN::cargar-ingredientes ()
  ; Ingredientes y categorías
  (make-instance ic1 of MAIN::ingredient-category (ingredient "chicken") (category meat))
  (make-instance ic2 of MAIN::ingredient-category (ingredient "beef") (category meat))
  (make-instance ic3 of MAIN::ingredient-category (ingredient "steak") (category meat))
  (make-instance ic4 of MAIN::ingredient-category (ingredient "lamb") (category meat))
  (make-instance ic5 of MAIN::ingredient-category (ingredient "bacon") (category meat))
  (make-instance ic6 of MAIN::ingredient-category (ingredient "ham") (category meat))
  (make-instance ic7 of MAIN::ingredient-category (ingredient "pork") (category meat))
  (make-instance ic8 of MAIN::ingredient-category (ingredient "sausage") (category meat))
  (make-instance ic9 of MAIN::ingredient-category (ingredient "meat") (category meat))
  (make-instance ic10 of MAIN::ingredient-category (ingredient "fish") (category fish))
  (make-instance ic11 of MAIN::ingredient-category (ingredient "salmon") (category fish))
  (make-instance ic12 of MAIN::ingredient-category (ingredient "tuna") (category fish))
  (make-instance ic13 of MAIN::ingredient-category (ingredient "cod") (category fish))
  (make-instance ic14 of MAIN::ingredient-category (ingredient "trout") (category fish))
  (make-instance ic15 of MAIN::ingredient-category (ingredient "halibut") (category fish))
  (make-instance ic16 of MAIN::ingredient-category (ingredient "shrimp") (category seafood))
  (make-instance ic17 of MAIN::ingredient-category (ingredient "prawns") (category seafood))
  (make-instance ic18 of MAIN::ingredient-category (ingredient "scallops") (category seafood))
  (make-instance ic19 of MAIN::ingredient-category (ingredient "lobster") (category seafood))
  (make-instance ic20 of MAIN::ingredient-category (ingredient "crab") (category seafood))
  (make-instance ic21 of MAIN::ingredient-category (ingredient "mussels") (category seafood))
  (make-instance ic22 of MAIN::ingredient-category (ingredient "clams") (category seafood))
  (make-instance ic23 of MAIN::ingredient-category (ingredient "seafood") (category seafood))
  (make-instance ic24 of MAIN::ingredient-category (ingredient "cheese") (category dairy))
  (make-instance ic25 of MAIN::ingredient-category (ingredient "milk") (category dairy))
  (make-instance ic26 of MAIN::ingredient-category (ingredient "cream") (category dairy))
  (make-instance ic27 of MAIN::ingredient-category (ingredient "butter") (category dairy))
  (make-instance ic28 of MAIN::ingredient-category (ingredient "parmesan") (category dairy))
  (make-instance ic29 of MAIN::ingredient-category (ingredient "yogurt") (category dairy))
  (make-instance ic30 of MAIN::ingredient-category (ingredient "egg") (category egg))
  (make-instance ic31 of MAIN::ingredient-category (ingredient "eggs") (category egg))
  (make-instance ic32 of MAIN::ingredient-category (ingredient "wheat") (category gluten))
  (make-instance ic33 of MAIN::ingredient-category (ingredient "bread") (category gluten))
  (make-instance ic34 of MAIN::ingredient-category (ingredient "pasta") (category gluten))
  (make-instance ic35 of MAIN::ingredient-category (ingredient "flour") (category gluten))
  (make-instance ic36 of MAIN::ingredient-category (ingredient "fettuccine") (category gluten))
  (make-instance ic37 of MAIN::ingredient-category (ingredient "noodles") (category gluten))
  (make-instance ic38 of MAIN::ingredient-category (ingredient "nuts") (category nuts))
  (make-instance ic39 of MAIN::ingredient-category (ingredient "walnuts") (category nuts))
  (make-instance ic40 of MAIN::ingredient-category (ingredient "almonds") (category nuts))
  (make-instance ic41 of MAIN::ingredient-category (ingredient "peanuts") (category nuts))
  (make-instance ic42 of MAIN::ingredient-category (ingredient "cashews") (category nuts))
  (make-instance ic43 of MAIN::ingredient-category (ingredient "hazelnuts") (category nuts))
  (make-instance ic44 of MAIN::ingredient-category (ingredient "soy") (category soy))
  (make-instance ic45 of MAIN::ingredient-category (ingredient "tofu") (category soy))
  (make-instance ic46 of MAIN::ingredient-category (ingredient "soya") (category soy))
  (make-instance ic47 of MAIN::ingredient-category (ingredient "tomatoes") (category vegetable) (seasons summer autumn))
  (make-instance ic48 of MAIN::ingredient-category (ingredient "basil") (category vegetable) (seasons summer))
  (make-instance ic49 of MAIN::ingredient-category (ingredient "garlic") (category vegetable) (seasons any))
  (make-instance ic50 of MAIN::ingredient-category (ingredient "olive_oil") (category vegetable) (seasons any))
  (make-instance ic51 of MAIN::ingredient-category (ingredient "spinach") (category vegetable) (seasons spring autumn winter))
  (make-instance ic52 of MAIN::ingredient-category (ingredient "artichoke") (category vegetable) (seasons spring))
  (make-instance ic53 of MAIN::ingredient-category (ingredient "mushrooms") (category vegetable) (seasons autumn))
  (make-instance ic54 of MAIN::ingredient-category (ingredient "lettuce") (category vegetable) (seasons spring summer))
  (make-instance ic55 of MAIN::ingredient-category (ingredient "onion") (category vegetable) (seasons any))
  (make-instance ic56 of MAIN::ingredient-category (ingredient "zucchini") (category vegetable) (seasons summer))
  (make-instance ic57 of MAIN::ingredient-category (ingredient "potato") (category vegetable) (seasons any))
  (make-instance ic58 of MAIN::ingredient-category (ingredient "pepper") (category vegetable) (seasons summer autumn))
  (make-instance ic59 of MAIN::ingredient-category (ingredient "cucumber") (category vegetable) (seasons summer))
  (make-instance ic60 of MAIN::ingredient-category (ingredient "eggplant") (category vegetable) (seasons summer autumn))
  (make-instance ic61 of MAIN::ingredient-category (ingredient "carrot") (category vegetable) (seasons autumn winter))
  (make-instance ic62 of MAIN::ingredient-category (ingredient "broccoli") (category vegetable) (seasons autumn winter))
  (make-instance ic63 of MAIN::ingredient-category (ingredient "cauliflower") (category vegetable) (seasons autumn winter))
  (make-instance ic64 of MAIN::ingredient-category (ingredient "asparagus") (category vegetable) (seasons spring))
  (make-instance ic65 of MAIN::ingredient-category (ingredient "celery") (category vegetable) (seasons autumn winter))
  (make-instance ic66 of MAIN::ingredient-category (ingredient "vegetables") (category vegetable) (seasons any))
  (make-instance ic67 of MAIN::ingredient-category (ingredient "fruit") (category fruit) (seasons any))
  (make-instance ic68 of MAIN::ingredient-category (ingredient "lemon") (category fruit) (seasons winter spring))
  (make-instance ic69 of MAIN::ingredient-category (ingredient "orange") (category fruit) (seasons winter))
  (make-instance ic70 of MAIN::ingredient-category (ingredient "apple") (category fruit) (seasons autumn))
  (make-instance ic71 of MAIN::ingredient-category (ingredient "avocado") (category fruit) (seasons spring summer))
  (make-instance ic72 of MAIN::ingredient-category (ingredient "strawberry") (category fruit) (seasons spring summer))
  (make-instance ic73 of MAIN::ingredient-category (ingredient "raspberry") (category fruit) (seasons summer))
  (make-instance ic74 of MAIN::ingredient-category (ingredient "banana") (category fruit) (seasons year_round))
  (make-instance ic75 of MAIN::ingredient-category (ingredient "berries") (category fruit) (seasons summer))
  (make-instance ic76 of MAIN::ingredient-category (ingredient "oil") (category vegetable) (seasons any))
  (make-instance ic77 of MAIN::ingredient-category (ingredient "sugar") (category vegetable) (seasons any))
  (make-instance ic78 of MAIN::ingredient-category (ingredient "honey") (category vegetable) (seasons any))
  (make-instance ic79 of MAIN::ingredient-category (ingredient "salt") (category vegetable) (seasons any))
  (make-instance ic80 of MAIN::ingredient-category (ingredient "rosemary") (category vegetable) (seasons any))
  (make-instance ic81 of MAIN::ingredient-category (ingredient "dill") (category vegetable) (seasons summer))
  (make-instance ic82 of MAIN::ingredient-category (ingredient "chocolate") (category vegetable) (seasons summer))
  (make-instance ic83 of MAIN::ingredient-category (ingredient "coconut_milk") (category vegetable) (seasons any))
  (make-instance ic84 of MAIN::ingredient-category (ingredient "coconut") (category vegetable) (seasons any))
  (make-instance ic85 of MAIN::ingredient-category (ingredient "truffle") (category vegetable) (seasons autumn winter))
  (make-instance ic86 of MAIN::ingredient-category (ingredient "sauce") (category vegetable) (seasons any))
  (make-instance ic87 of MAIN::ingredient-category (ingredient "confidential") (category vegetable) (seasons any))
  (make-instance ic88 of MAIN::ingredient-category (ingredient "alfredo_sauce") (category vegetable) (seasons any))
)
