; =================================
; DISH DATA - AUTOMATICALLY GENERATED
; =================================

(deftemplate dish
  (slot id)
  (slot course)
  (multislot ingredients)
  (multislot diets)
  (slot price (type FLOAT)))

(deftemplate ingredient-category
  (slot ingredient)
  (slot category))

; INGREDIENT CATEGORIES
(deffacts ingredient-categories
  (ingredient-category (ingredient "chicken") (category meat))
  (ingredient-category (ingredient "beef") (category meat))
  (ingredient-category (ingredient "steak") (category meat))
  (ingredient-category (ingredient "lamb") (category meat))
  (ingredient-category (ingredient "bacon") (category meat))
  (ingredient-category (ingredient "ham") (category meat))
  (ingredient-category (ingredient "pork") (category meat))
  (ingredient-category (ingredient "sausage") (category meat))
  (ingredient-category (ingredient "meat") (category meat))
  (ingredient-category (ingredient "fish") (category fish))
  (ingredient-category (ingredient "salmon") (category fish))
  (ingredient-category (ingredient "tuna") (category fish))
  (ingredient-category (ingredient "cod") (category fish))
  (ingredient-category (ingredient "trout") (category fish))
  (ingredient-category (ingredient "halibut") (category fish))
  (ingredient-category (ingredient "shrimp") (category seafood))
  (ingredient-category (ingredient "prawns") (category seafood))
  (ingredient-category (ingredient "scallops") (category seafood))
  (ingredient-category (ingredient "lobster") (category seafood))
  (ingredient-category (ingredient "crab") (category seafood))
  (ingredient-category (ingredient "mussels") (category seafood))
  (ingredient-category (ingredient "clams") (category seafood))
  (ingredient-category (ingredient "seafood") (category seafood))
  (ingredient-category (ingredient "cheese") (category dairy))
  (ingredient-category (ingredient "milk") (category dairy))
  (ingredient-category (ingredient "cream") (category dairy))
  (ingredient-category (ingredient "butter") (category dairy))
  (ingredient-category (ingredient "parmesan") (category dairy))
  (ingredient-category (ingredient "yogurt") (category dairy))
  (ingredient-category (ingredient "egg") (category egg))
  (ingredient-category (ingredient "eggs") (category egg))
  (ingredient-category (ingredient "wheat") (category gluten))
  (ingredient-category (ingredient "bread") (category gluten))
  (ingredient-category (ingredient "pasta") (category gluten))
  (ingredient-category (ingredient "flour") (category gluten))
    (ingredient-category (ingredient "fettuccine") (category gluten))
    (ingredient-category (ingredient "noodles") (category gluten))
    (ingredient-category (ingredient "nuts") (category nuts))
    (ingredient-category (ingredient "walnuts") (category nuts))
    (ingredient-category (ingredient "almonds") (category nuts))
    (ingredient-category (ingredient "peanuts") (category nuts))
    (ingredient-category (ingredient "cashews") (category nuts))
    (ingredient-category (ingredient "hazelnuts") (category nuts))
(ingredient-category (ingredient "soy") (category soy))
(ingredient-category (ingredient "tofu") (category soy))
(ingredient-category (ingredient "soya") (category soy))
(ingredient-category (ingredient "tomatoes") (category vegetable))
(ingredient-category (ingredient "basil") (category vegetable))
(ingredient-category (ingredient "garlic") (category vegetable))
(ingredient-category (ingredient "olive_oil") (category vegetable))
(ingredient-category (ingredient "spinach") (category vegetable))
(ingredient-category (ingredient "artichoke") (category vegetable))
(ingredient-category (ingredient "mushrooms") (category vegetable))
(ingredient-category (ingredient "lettuce") (category vegetable))
(ingredient-category (ingredient "onion") (category vegetable))
(ingredient-category (ingredient "zucchini") (category vegetable))
(ingredient-category (ingredient "potato") (category vegetable))
(ingredient-category (ingredient "pepper") (category vegetable))
(ingredient-category (ingredient "cucumber") (category vegetable))
(ingredient-category (ingredient "eggplant") (category vegetable))
(ingredient-category (ingredient "carrot") (category vegetable))
(ingredient-category (ingredient "broccoli") (category vegetable))
(ingredient-category (ingredient "cauliflower") (category vegetable))
(ingredient-category (ingredient "asparagus") (category vegetable))
(ingredient-category (ingredient "celery") (category vegetable))
(ingredient-category (ingredient "vegetables") (category vegetable))
(ingredient-category (ingredient "fruit") (category fruit))
(ingredient-category (ingredient "lemon") (category fruit))
(ingredient-category (ingredient "orange") (category fruit))
(ingredient-category (ingredient "apple") (category fruit))
(ingredient-category (ingredient "avocado") (category fruit))
(ingredient-category (ingredient "strawberry") (category fruit))
(ingredient-category (ingredient "raspberry") (category fruit))
(ingredient-category (ingredient "banana") (category fruit))
(ingredient-category (ingredient "berries") (category fruit))
(ingredient-category (ingredient "oil") (category vegetable))
(ingredient-category (ingredient "sugar") (category vegetable))
(ingredient-category (ingredient "honey") (category vegetable))
(ingredient-category (ingredient "salt") (category vegetable))
(ingredient-category (ingredient "rosemary") (category vegetable))
(ingredient-category (ingredient "dill") (category vegetable))
(ingredient-category (ingredient "chocolate") (category vegetable))
(ingredient-category (ingredient "coconut_milk") (category vegetable))
(ingredient-category (ingredient "coconut") (category vegetable))
(ingredient-category (ingredient "truffle") (category vegetable))
(ingredient-category (ingredient "sauce") (category vegetable))
(ingredient-category (ingredient "confidential") (category vegetable))
(ingredient-category (ingredient "alfredo_sauce") (category vegetable))
)

; MENU DISHES
(deffacts dishes
(dish (id "soda_R003_0") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.55))
(dish (id "spinach_artichoke_dip_R001_1") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.12))
(dish (id "new_york_cheesecake_R003_2") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.66))
(dish (id "chicken_alfredo_R003_3") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 29.55))
(dish (id "grilled_steak_R002_4") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 17.73))
(dish (id "stuffed_mushrooms_R001_5") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.28))
(dish (id "soda_R001_6") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.87))
(dish (id "tiramisu_R003_7") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 10.47))
(dish (id "grilled_steak_R003_8") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 26.78))
(dish (id "lemonade_R003_9") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.95))
(dish (id "chocolate_lava_cake_R001_10") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 16.08))
(dish (id "spinach_artichoke_dip_R001_11") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.09))
(dish (id "iced_tea_R001_12") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.43))
(dish (id "chicken_alfredo_R001_13") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 18.46))
(dish (id "lemonade_R003_14") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.83))
(dish (id "tiramisu_R003_15") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.91))
(dish (id "coffee_R002_16") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.94))
(dish (id "grilled_steak_R002_17") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.52))
(dish (id "tiramisu_R001_18") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.75))
(dish (id "grilled_steak_R002_19") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 28.90))
(dish (id "lemonade_R003_20") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.27))
(dish (id "soda_R003_21") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.88))
(dish (id "soda_R001_22") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.81))
(dish (id "iced_tea_R001_23") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.90))
(dish (id "bruschetta_R001_24") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 13.62))
(dish (id "spinach_artichoke_dip_R001_25") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 10.96))
(dish (id "coffee_R001_26") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.02))
(dish (id "chocolate_lava_cake_R003_27") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.11))
(dish (id "spinach_artichoke_dip_R003_28") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.52))
(dish (id "chicken_alfredo_R003_29") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 28.72))
(dish (id "coffee_R001_30") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_31") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_32") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_33") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_34") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_35") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_36") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_37") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_38") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_39") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_40") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_41") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_42") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_43") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_44") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_45") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_46") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_47") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_48") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_49") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_50") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_51") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_52") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_53") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_54") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_55") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_56") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_57") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_58") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_59") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_60") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_61") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_62") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_63") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "soda_R003_64") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.07))
(dish (id "vegetable_stir-fry_R003_65") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 17.06))
(dish (id "caprese_salad_R001_66") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 14.47))
(dish (id "shrimp_scampi_R002_67") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 18.43))
(dish (id "soda_R002_68") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.55))
(dish (id "chicken_alfredo_R001_69") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 16.40))
(dish (id "stuffed_mushrooms_R001_70") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.43))
(dish (id "spinach_artichoke_dip_R001_71") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.90))
(dish (id "coffee_R003_72") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.21))
(dish (id "coffee_R001_73") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.25))
(dish (id "coffee_R002_74") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.74))
(dish (id "spinach_artichoke_dip_R002_75") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 14.82))
(dish (id "iced_tea_R002_76") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.65))
(dish (id "fruit_tart_R003_77") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.94))
(dish (id "vegetable_stir-fry_R003_78") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_79") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_80") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_81") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_82") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_83") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_84") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_85") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_86") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_87") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_88") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_89") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_90") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_91") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_92") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_93") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_94") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_95") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_96") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_97") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_98") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_99") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_100") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_101") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_102") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_103") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_104") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_105") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_106") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_107") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_108") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_109") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_110") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_111") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_112") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_113") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_114") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_115") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_116") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_117") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_118") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_119") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_120") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_121") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_122") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_123") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_124") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_125") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_126") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_127") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_128") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_129") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_130") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_131") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_132") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_133") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_134") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_135") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_136") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_137") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_138") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_139") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_140") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_141") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_142") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_143") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_144") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_145") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_146") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_147") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_148") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_149") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_150") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_151") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_152") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_153") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_154") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_155") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_156") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_157") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_158") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_159") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_160") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_161") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_162") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_163") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_164") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_165") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_166") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_167") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_168") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_169") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_170") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_171") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_172") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_173") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_174") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_175") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_176") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_177") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_178") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_179") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_180") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_181") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_182") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_183") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_184") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_185") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_186") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_187") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_188") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_189") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_190") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_191") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_192") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_193") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_194") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_195") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_196") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_197") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_198") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_199") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_200") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_201") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_202") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_203") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_204") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_205") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_206") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_207") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_208") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_209") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_210") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_211") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_212") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_213") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_214") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_215") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_216") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_217") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_218") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_219") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_220") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_221") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_222") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_223") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_224") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_225") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_226") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_227") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_228") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_229") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_230") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_231") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_232") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_233") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_234") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_235") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_236") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_237") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_238") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_239") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_240") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_241") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_242") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_243") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_244") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_245") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_246") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_247") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_248") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_249") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_250") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_251") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_252") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_253") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_254") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_255") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_256") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_257") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_258") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_259") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_260") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_261") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_262") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_263") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_264") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_265") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_266") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_267") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_268") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_269") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_270") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_271") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_272") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_273") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_274") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_275") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_276") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_277") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_278") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_279") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_280") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_281") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_282") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_283") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_284") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_285") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_286") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_287") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_288") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_289") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_290") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_291") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_292") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_293") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_294") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_295") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_296") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_297") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_298") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_299") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_300") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_301") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_302") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_303") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_304") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_305") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_306") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_307") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_308") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_309") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_310") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_311") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_312") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_313") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_314") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_315") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_316") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_317") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_318") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_319") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_320") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_321") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_322") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_323") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_324") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_325") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_326") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_327") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_328") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_329") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_330") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_331") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_332") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_333") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_334") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_335") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_336") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_337") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_338") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_339") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_340") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_341") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_342") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_343") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_344") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_345") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_346") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_347") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_348") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_349") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_350") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_351") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_352") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_353") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_354") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_355") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_356") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_357") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_358") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_359") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_360") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_361") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_362") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_363") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_364") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_365") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_366") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_367") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_368") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_369") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_370") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_371") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_372") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_373") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_374") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_375") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_376") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_377") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_378") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_379") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_380") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_381") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_382") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_383") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_384") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_385") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_386") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_387") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_388") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_389") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_390") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_391") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_392") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_393") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_394") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_395") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_396") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_397") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_398") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_399") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_400") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_401") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_402") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_403") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_404") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_405") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_406") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_407") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_408") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_409") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_410") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_411") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_412") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_413") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_414") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_415") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_416") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_417") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_418") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_419") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_420") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_421") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_422") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_423") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_424") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_425") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_426") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_427") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_428") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_429") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_430") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_431") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_432") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_433") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_434") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_435") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_436") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_437") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_438") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_439") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_440") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_441") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_442") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_443") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_444") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_445") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_446") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_447") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_448") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_449") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_450") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_451") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_452") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_453") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_454") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_455") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_456") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_457") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_458") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_459") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_460") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_461") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_462") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_463") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_464") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_465") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "spinach_artichoke_dip_R002_466") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.23))
(dish (id "chocolate_lava_cake_R003_467") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.29))
(dish (id "new_york_cheesecake_R003_468") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.61))
(dish (id "chicken_alfredo_R002_469") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.43))
(dish (id "vegetable_stir-fry_R001_470") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.06))
(dish (id "shrimp_scampi_R002_471") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 19.87))
(dish (id "soda_R003_472") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.95))
(dish (id "bruschetta_R001_473") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.53))
(dish (id "soda_R001_474") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 4.58))
(dish (id "vegetable_stir-fry_R003_475") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.01))
(dish (id "bruschetta_R002_476") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "tiramisu_R003_477") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.19))
(dish (id "soda_R001_478") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.19))
(dish (id "coffee_R002_479") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.76))
(dish (id "chocolate_lava_cake_R002_480") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.48))
(dish (id "chocolate_lava_cake_R001_481") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 19.77))
(dish (id "chocolate_lava_cake_R002_482") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.45))
(dish (id "tiramisu_R001_483") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.45))
(dish (id "iced_tea_R002_484") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.73))
(dish (id "fruit_tart_R003_485") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 12.38))
(dish (id "vegetable_stir-fry_R003_486") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 22.05))
(dish (id "grilled_steak_R002_487") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 23.04))
(dish (id "stuffed_mushrooms_R001_488") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 11.56))
(dish (id "fruit_tart_R001_489") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.26))
(dish (id "shrimp_scampi_R003_490") (course main) (ingredients chicken fettuccine alfredo_sauce parmesan) (diets egg_free seafood_free nut_free) (price 27.14))
(dish (id "coffee_R001_491") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.99))
(dish (id "tiramisu_R003_492") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 13.25))
(dish (id "coffee_R003_493") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 2.82))
(dish (id "spinach_artichoke_dip_R003_494") (course appetizer) (ingredients tomatoes basil garlic olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.84))
(dish (id "chocolate_lava_cake_R002_495") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 17.22))
(dish (id "tiramisu_R003_496") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 14.94))
(dish (id "new_york_cheesecake_R001_497") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 11.11))
(dish (id "new_york_cheesecake_R001_498") (course dessert) (ingredients chocolate butter sugar eggs) (diets vegetarian gluten_free seafood_free nut_free) (price 18.96))
(dish (id "soda_R001_499") (course beverage) (ingredients confidential) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 3.53))
(dish (id "vegan_chocolate_cake_X1") (course dessert) (ingredients chocolate coconut_milk sugar) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 12.50))
(dish (id "vegan_berry_mousse_X2") (course dessert) (ingredients raspberry strawberry coconut_milk sugar) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 13.00))
(dish (id "vegan_chickpea_curry_X3") (course main) (ingredients chickpea tomato onion garlic coconut_milk) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 15.50))
(dish (id "vegan_veggie_lasagna_X4") (course main) (ingredients zucchini eggplant tomato spinach olive_oil) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 16.00))
(dish (id "vegan_hummus_crudites_X5") (course appetizer) (ingredients chickpea garlic olive_oil carrot cucumber) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 8.50))
(dish (id "vegan_quinoa_salad_X6") (course appetizer) (ingredients quinoa tomato cucumber olive_oil lemon) (diets vegan vegetarian lactose_free gluten_free egg_free seafood_free nut_free) (price 9.00))
)